apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptrain-server-claim
  labels:
    {{- include "uptrain.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi